name: Build ynoengine
on:
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          REPO="${{ github.repository }}"
          docker run -v $(pwd):/root/workdir/ynoengine:rw -e PLAYER_PSK="${{ secrets.PSK }}" ghcr.io/${REPO,,}:master
          docker run -v $(pwd):/root/workdir/ynoengine:rw -e PLAYER_PSK="${{ secrets.PSK }}" -e NO_SIMD=1 ghcr.io/${REPO,,}:master
          echo "TAG=$(date +'%Y-%m-%d.%H.%M.%S')" >> $GITHUB_ENV
      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.TAG }}
          files: |
            build/ynoengine.js
            build/ynoengine.wasm
            build/ynoengine-simd.js
            build/ynoengine-simd.wasm
